### ISSUE TITLE
Merge into http-more?

### ISSUE THREAD

**Issue by dandv** [aldeed/meteor-http-extras#1]
I've had similar problems with MDG taking its time to implement PRs for the http package and published `http-more`. https://github.com/dandv/meteor-http-more#features

**Comment by aldeed** [comment]
This package is no longer maintained. Now that Meteor apps can use NPM packages directly, I recommend using a more standards-based package such as [isomorphic-fetch](https://www.npmjs.com/package/isomorphic-fetch) rather than Meteor's HTTP package.
