### ISSUE TITLE
The provided value 'undefined' is not a valid enum value of interface XMLHttpRequestResponseType. 

### ISSUE THREAD

**Issue by chafey** [aldeed/meteor-http-extras#7]
Chrome is issuing this warning for my calls that don't specify the responseType.  Can we add a check to only set it if it is provided so it is compatible with existing code using meteor Http calls?  I can submit a PR if needed, but its a small change

**Comment by chafey** [comment]
PR #8

**Comment by danopia** [comment]
Yea, a simple condition on the else would fix this. I'd like to have my terminal cleaner so I can see actual problems easier, so ideally something can be released soon

**Comment by Ajaxsoap** [comment]
Same here, for me when importing csv file, no error on the console and on browser console it throws this warning message.

**Comment by bluepuma77** [comment]
@aldeed Would it be possible to create a new release with the pull request? A lot of people using (deprecated) CollectionFS are having an issue with this: https://github.com/CollectionFS/Meteor-CollectionFS/issues/688

**Comment by aldeed** [comment]
This package is no longer maintained. Now that Meteor apps can use NPM packages directly, I recommend using a more standards-based package such as [isomorphic-fetch](https://www.npmjs.com/package/isomorphic-fetch) rather than Meteor's HTTP package.
