### ISSUE TITLE
No support for option beforeSend

### ISSUE THREAD

**Issue by dsiebes** [aldeed/meteor-http-extras#9]
Hello, this is a great package. It, however, does not currently support Meteor's new beforeSend option in the base http package. (Meteor 1.2.1, http 1.1.1).

To replicate:

httpProgress = function(xhr) {
    console.log('this never executes');
}
var url = 'http://www.google.com';
HTTP.call('GET',url, {
        beforeSend: httpProgress,
        headers: {
            'Accept': '_/_'
        },
        responseType: 'arraybuffer'
    }, function(error, result) {
...
});

I'm happy to donate for the feature :+1:

**Comment by aldeed** [comment]
This package is no longer maintained. Now that Meteor apps can use NPM packages directly, I recommend using a more standards-based package such as [isomorphic-fetch](https://www.npmjs.com/package/isomorphic-fetch) rather than Meteor's HTTP package.
